# Etude du DF total

## Importer les librairies

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re

### Obtenir l'info complète du DF

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
#pd.set_option('display.max_colwidth', None)

## Importer le DF

In [3]:
df= pd.read_csv("gaming_total.csv", index_col=0)
df.head()

C:\Users\debor\AppData\Local\Temp\ipykernel_64112\60888040.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv("gaming_total.csv", index_col=0)

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,developpeur_goo,distributeur_goo,langue_goo,PEGI_goo,game_series_goo,game_mode_goo,developpeur_wiki,langue_wiki,PEGI_wiki,game_mode_wiki,Meta_NP,Meta_VP,Meta_NUsers,Meta_VUsers,summary,meta_score,user_review,Rank,test_note_JVC,avis_count_JVC,avis_note_JVC,Classification_Age_JVC,max_joueurs_JVC,Mode_JVC,Support_JVC,Langue_JVC
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,"Nintendo, PLUS",NaN,NaN,NaN,NaN,NaN,Nintendo EAD,Multilingue,7+ ?,Un joueur\r\nMultijoueur (de 2 à 4),76.0,51.0,8.1,539.0,Tennis (1-4 players): Players grab the control...,76.0,8.1,1.0,14,(687),13.8,+7 ans\r,Jusqu'à 4 joueurs\r,NaN,DVD\r,Voix en français Textes en français
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,Universal Pictures,Anglais,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,14.0,8.4,119.0,NaN,NaN,NaN,NaN,19,(3),19,+3 ans\r,NaN,Jouable en solo\r,eShop Console Virtuelle Cartouche\r,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,NaN,NaN,NaN,NaN,NaN,NaN,Nintendo EAD,Multilingue,3+ ?,Local\r\n1 à 4 joueurs\r\nEn ligne (jusqu'au 2...,82.0,73.0,8.5,1167.0,Mario Kart Wii comes with the intuitive Wii Wh...,82.0,8.4,3.0,16,(3023),17.4,+3 ans\r,"4 joueurs en écran partagé, 12 joueurs online\r",Multi sur le même écran Multi en ligne\r,DVD\r,NaN
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,"Nintendo, Nintendo Entertainment Analysis & De...",NaN,NaN,NaN,NaN,Multijoueur,NaN,NaN,NaN,NaN,80.0,73.0,8.3,346.0,Wii Sports Resort is a collection of fun sport...,80.0,8.2,4.0,15,(581),16.5,+3 ans\r,Jusqu'à 4 joueurs\r,NaN,DVD\r,Voix en français Textes en français\r
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no_data,no_data,no_data,NaN,NaN,NaN,NaN,NaN

In [4]:
df = df.replace('no_data', np.nan)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16628 entries, 0 to 16630
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    16628 non-null  object
 1   Platform                16628 non-null  object
 2   Year                    16358 non-null  float64
 3   Genre                   16628 non-null  object
 4   Publisher               16570 non-null  object
 5   NA_Sales                16628 non-null  float64
 6   EU_Sales                16628 non-null  float64
 7   JP_Sales                16628 non-null  float64
 8   Other_Sales             16628 non-null  float64
 9   Global_Sales            16628 non-null  float64
 10  developpeur_goo         1500 non-null   object
 11  distributeur_goo        14 non-null     object
 12  langue_goo              75 non-null     object
 13  PEGI_goo                503 non-null    object
 14  game_series_goo         524 non-null    object
 15  game_mode_goo           845 non-null    object
 16  developpeur_wiki        3095 non-null   object
 17  langue_wiki             1436 non-null   object
 18  PEGI_wiki               1085 non-null   object
 19  game_mode_wiki          2837 non-null   object
 20  Meta_NP                 10832 non-null  float64
 21  Meta_VP                 10862 non-null  float64
 22  Meta_NUsers             9958 non-null   float64
 23  Meta_VUsers             9958 non-null   float64
 24  summary                 5191 non-null   object
 25  meta_score              5194 non-null   float64
 26  user_review             5194 non-null   object
 27  Rank                    5194 non-null   float64
 28  test_note_JVC           10032 non-null  object
 29  avis_count_JVC          9133 non-null   object
 30  avis_note_JVC           9133 non-null   object
 31  Classification_Age_JVC  7111 non-null   object
 32  max_joueurs_JVC         4179 non-null   object
 33  Mode_JVC                3933 non-null   object
 34  Support_JVC             7369 non-null   object
 35  Langue_JVC              4618 non-null   object
dtypes: float64(12), object(24)
memory usage: 4.7+ MB

In [6]:
# définir une expression régulière pour extraire les 2 premiers mots qui suivent "voix"
pattern = re.compile(r'\bvoix\W+(\w+\W+){0,1}\w+\b', flags=re.IGNORECASE)

# extraire les 2 premiers mots qui suivent "voix" pour chaque chaîne de caractères
df['langue_parlée_JVC'] = df['Langue_JVC'].apply(lambda x: pattern.search(str(x)).group(0) if pattern.search(str(x)) else None)

# définir une expression régulière pour extraire les 2 premiers mots qui suivent "Textes"
pattern = re.compile(r'\btextes\W+(\w+\W+){0,1}\w+\b', flags=re.IGNORECASE)

# extraire les 2 premiers mots qui suivent "Textes" pour chaque chaîne de caractères
df['texte_JVC'] = df['Langue_JVC'].apply(lambda x: pattern.search(str(x)).group(0) if pattern.search(str(x)) else None)

In [7]:
# fonction pour extraire le premier chiffre d'une chaîne de caractères
def extract_first_number(s):
    match = re.search(r'\d+', s)
    if match:
        return int(match.group())
    else:
        return None

# appliquer la fonction à la colonne 'max_joueurs' pour extraire le premier chiffre
df['max_joueurs_JVC'] = df['max_joueurs_JVC'].apply(lambda x: extract_first_number(str(x)))
df['nb_joueurs_JVC'] = df['max_joueurs_JVC'].apply(lambda x: extract_first_number(str(x)))
df['PEGI_goo'] = df['PEGI_goo'].apply(lambda x: extract_first_number(str(x)))
df['Classification_Age_JVC'] = df['Classification_Age_JVC'].apply(lambda x: extract_first_number(str(x)))
df['PEGI_wiki'] = df['PEGI_wiki'].apply(lambda x: extract_first_number(str(x)))

In [8]:
df['avis_count_JVC']= df['avis_count_JVC'].apply(lambda x: x.replace('(', '').replace(')', '') if isinstance(x, str) else x)
df['Mode_JVC']= df['Mode_JVC'].apply(lambda x: x.replace('\r', '') if isinstance(x, str) else x)
df['Support_JVC']= df['Support_JVC'].apply(lambda x: x.replace('\r', '') if isinstance(x, str) else x)
df['game_mode_wiki']= df['game_mode_wiki'].apply(lambda x: x.replace('\r', '').replace('\n', '') if isinstance(x, str) else x)

In [9]:
df['test_note_JVC']=df['test_note_JVC'].replace('--','11')
df['test_note_JVC']= df['test_note_JVC'].astype('float')
df['avis_count_JVC']= df['avis_count_JVC'].astype('float')
df['avis_note_JVC']=df['avis_note_JVC'].replace('--','15')
df['avis_note_JVC']= df['avis_note_JVC'].astype('float')

In [10]:
# extraire la langue
for i, row in df.iterrows():
    if not pd.isnull(row['langue_parlée_JVC']):
        df.at[i, 'langue_parlée_JVC'] = row['langue_parlée_JVC'].split()[2]

In [11]:
# extraire la langue du texte
for i, row in df.iterrows():
    if not pd.isnull(row['texte_JVC']):
        df.at[i, 'texte_JVC'] = row['texte_JVC'].split()[2]

In [12]:
# extraire le developpeur
for i, row in df.iterrows():
    if not pd.isnull(row['developpeur_goo']):
        df.at[i, 'developpeur_goo'] = row['developpeur_goo'].split()[0]

df['developpeur_goo']=df['developpeur_goo'].str.replace(',', '').str.replace(';', '')

In [13]:
# extraire la langue
for i, row in df.iterrows():
    if not pd.isnull(row['langue_goo']):
        df.at[i, 'langue_goo'] = row['langue_goo'].split()[0]
df['langue_goo']=df['langue_goo'].str.replace(',', '').str.replace(';', '').str.replace('.', '')
df['langue_goo']=df['langue_goo'].replace('Voix', None).replace('*Sous-titres', None)
#df['langue_goo'] = df['langue_goo'].apply(lambda x: x.astype(str).str.upper())

C:\Users\debor\AppData\Local\Temp\ipykernel_64112\726182482.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['langue_goo']=df['langue_goo'].str.replace(',', '').str.replace(';', '').str.replace('.', '')

In [14]:
# définir une fonction qui prend une valeur et renvoie 2 si elle répond à vos critères, 1 sinon, et None si c'est un NaN
def categorize_mode_de_jeu(value):
    if pd.isna(value):
        return None
    elif 'joueurs' in value or 'multijoueur' in value or any(char.isdigit() for char in value):
        return 2
    else:
        return 1

# appliquer la fonction à chaque élément de la colonne "mode_de_jeu" pour créer une nouvelle colonne "categorie"
df['game_mode'] = df['game_mode_wiki'].apply(categorize_mode_de_jeu)

In [15]:
df['user_review']=df['user_review'].replace('tbd',None)
df['user_review']=df['user_review'].astype(float)

In [16]:
# définir une fonction qui prend une valeur et renvoie 2 si elle répond à vos critères, 1 sinon, et None si c'est un NaN
def categorize_mode_de_jeu_2(value):
    if pd.isna(value):
        return None
    elif 'Multi' in value or any(char.isdigit() for char in value):
        return 2
    else:
        return 1

# appliquer la fonction à chaque élément de la colonne "mode_de_jeu" pour créer une nouvelle colonne "categorie"
df['game_mode_JVC'] = df['Mode_JVC'].apply(categorize_mode_de_jeu_2)

In [17]:
df['game_mode_JVC'].value_counts()

1.0    2304
2.0    1629
Name: game_mode_JVC, dtype: int64

In [18]:
df= df.drop(['Mode_JVC','summary','game_mode_wiki', 'Langue_JVC','langue_wiki', 'langue_goo', 'game_series_goo', 'game_mode_goo', 'distributeur_goo'], axis=1)

In [19]:
#df=df.drop(['Rank_x', 'Rank_y'], axis=1)

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16628 entries, 0 to 16630
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    16628 non-null  object
 1   Platform                16628 non-null  object
 2   Year                    16358 non-null  float64
 3   Genre                   16628 non-null  object
 4   Publisher               16570 non-null  object
 5   NA_Sales                16628 non-null  float64
 6   EU_Sales                16628 non-null  float64
 7   JP_Sales                16628 non-null  float64
 8   Other_Sales             16628 non-null  float64
 9   Global_Sales            16628 non-null  float64
 10  developpeur_goo         1500 non-null   object
 11  PEGI_goo                486 non-null    float64
 12  developpeur_wiki        3095 non-null   object
 13  PEGI_wiki               1083 non-null   float64
 14  Meta_NP                 10832 non-null  float64
 15  Meta_VP                 10862 non-null  float64
 16  Meta_NUsers             9958 non-null   float64
 17  Meta_VUsers             9958 non-null   float64
 18  meta_score              5194 non-null   float64
 19  user_review             4889 non-null   float64
 20  Rank                    5194 non-null   float64
 21  test_note_JVC           10032 non-null  float64
 22  avis_count_JVC          9133 non-null   float64
 23  avis_note_JVC           9133 non-null   float64
 24  Classification_Age_JVC  7111 non-null   float64
 25  max_joueurs_JVC         2566 non-null   float64
 26  Support_JVC             7369 non-null   object
 27  langue_parlée_JVC       3962 non-null   object
 28  texte_JVC               4616 non-null   object
 29  nb_joueurs_JVC          2566 non-null   float64
 30  game_mode               2837 non-null   float64
 31  game_mode_JVC           3933 non-null   float64
dtypes: float64(23), object(9)
memory usage: 4.7+ MB

In [20]:
df.to_csv('gaming_total_v2.csv')

In [21]:
df.describe(include='all')

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,developpeur_goo,PEGI_goo,developpeur_wiki,PEGI_wiki,Meta_NP,Meta_VP,Meta_NUsers,Meta_VUsers,meta_score,user_review,Rank,test_note_JVC,avis_count_JVC,avis_note_JVC,Classification_Age_JVC,max_joueurs_JVC,Support_JVC,langue_parlée_JVC,texte_JVC,nb_joueurs_JVC,game_mode,game_mode_JVC
count,16628,16628,16358.000000,16628,16570,16628.000000,16628.000000,16628.000000,16628.000000,16628.000000,1500,486.000000,3095,1083.000000,10832.000000,10862.000000,9958.000000,9958.000000,5194.000000,4889.000000,5194.000000,10032.000000,9133.000000,9133.000000,7111.000000,2566.000000,7369,3962,4616,2566.000000,2837.000000,3933.000000
unique,11493,31,NaN,12,578,NaN,NaN,NaN,NaN,NaN,527,NaN,977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,531,3,3,NaN,NaN,NaN
top,Need for Speed: Most Wanted,PS2,NaN,Action,Electronic Arts,NaN,NaN,NaN,NaN,NaN,Capcom,NaN,EA Tiburon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DVD,français,français,NaN,NaN,NaN
freq,12,2166,NaN,3333,1357,NaN,NaN,NaN,NaN,NaN,41,NaN,95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1848,2554,3841,NaN,NaN,NaN
mean,NaN,NaN,2006.410136,NaN,NaN,0.264508,0.146513,0.077641,0.048037,0.536973,NaN,41.261317,NaN,10.431210,69.138848,25.377555,7.210544,216.685479,73.089911,7.343894,6429.124759,12.389952,59.533560,14.800701,8.637041,3.056898,NaN,NaN,NaN,3.056898,1.511808,1.414188
std,NaN,NaN,5.825095,NaN,NaN,0.816007,0.504917,0.309029,0.188426,1.553710,NaN,253.680031,NaN,5.740992,13.802681,18.759078,1.327118,873.507812,11.882804,1.239521,4559.303045,2.890838,206.756847,3.185018,5.716143,6.034071,NaN,NaN,NaN,6.034071,0.499949,0.492644
min,NaN,NaN,1980.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.010000,NaN,3.000000,NaN,3.000000,12.000000,0.000000,0.600000,4.000000,22.000000,1.300000,1.000000,1.000000,0.000000,0.000000,3.000000,1.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000
25%,NaN,NaN,2003.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.060000,NaN,3.000000,NaN,3.000000,61.000000,11.000000,6.600000,13.000000,66.000000,6.800000,2453.500000,11.000000,2.000000,13.900000,3.000000,2.000000,NaN,NaN,NaN,2.000000,1.000000,1.000000
50%,NaN,NaN,2007.000000,NaN,NaN,0.080000,0.020000,0.000000,0.010000,0.170000,NaN,7.000000,NaN,12.000000,71.000000,20.000000,7.500000,33.000000,74.000000,7.600000,5586.500000,11.000000,7.000000,15.000000,7.000000,2.000000,NaN,NaN,NaN,2.000000,2.000000,1.000000
75%,NaN,NaN,2010.000000,NaN,NaN,0.240000,0.110000,0.040000,0.040000,0.470000,NaN,12.000000,NaN,16.000000,79.000000,35.000000,8.200000,107.000000,81.000000,8.200000,9950.250000,15.000000,34.000000,16.800000,12.000000,2.000000,NaN,NaN,NaN,2.000000,2.000000,2.000000
max,NaN,NaN,2020.000000,NaN,NaN,41.490000,29.020000,10.220000,10.570000,82.740000,NaN,2001.000000,NaN,18.000000,99.000000,122.000000,9.700000,31070.000000,99.000000,9.700000,16585.000000,19.000000,4560.000000,20.000000,18.000000,256.000000,NaN,NaN,NaN,256.000000,2.000000,2.000000